spring:
  datasource:
    url: jdbc:mysql://localhost:3306/finance
    username: root
    password: alfared
  server:
    port: 8080
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
